### ISSUE TITLE
Fails to build on Android for Nativescript 6.0.0

### ISSUE THREAD

**Issue by nikoTM** [nstudio/nativescript-pulltorefresh#57]
The build fails with the following error:

```
Exception in thread "main" java.lang.RuntimeException: Class not found android.support.v4.widget.SwipeRefreshLayout.OnRefreshListener
        at org.nativescript.staticbindinggenerator.Generator.getClass(Generator.java:549)
        at org.nativescript.staticbindinggenerator.Generator.getInterfacesFromCache(Generator.java:532)
        at org.nativescript.staticbindinggenerator.Generator.writeBinding(Generator.java:283)
        at org.nativescript.staticbindinggenerator.Generator.generateBinding(Generator.java:171)
        at org.nativescript.staticbindinggenerator.Generator.processRows(Generator.java:234)
        at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:121)
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:97)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:50)
```

**Comment by bradmartin** [comment]
Please update to `@nstudio/nativescript-pulltorefresh` with `tns plugin add @nstudio/nativescript-pulltorefresh` for AndroidX updates.
