### ISSUE TITLE
Class not found android.support.v4.widget.SwipeRefreshLayout.OnRefreshListener

### ISSUE THREAD

**Issue by programista25** [nstudio/nativescript-pulltorefresh#61]
After I've added your plugin to my xml file. I've got following error:
`[19-08-26 09:42:20.521] (CLI) Exception in thread "main"
[19-08-26 09:42:20.528] (CLI) java.lang.RuntimeException: Class not found android.support.v4.widget.SwipeRefreshLayout.OnRefreshListener
	at org.nativescript.staticbindinggenerator.Generator.getClass(Generator.java:549)
	at org.nativescript.staticbindinggenerator.Generator.getInterfacesFromCache(Generator.java:532)
	at org.nativescript.staticbindinggenerator.Generator.writeBinding(Generator.java:283)
	at org.nativescript.staticbindinggenerator.Generator.generateBinding(Generator.java:171)
	at org.nativescript.staticbindinggenerator.Generator.processRows(Generator.java:234)
	at org.nativescript.staticbindinggenerator.Generator.generateBindings(Generator.java:121)`
Note that I'm using latest version of Nativescript (6.0)

My xml code is:
`<Page class="page" navigatingTo="onNavigatingTo" loaded="onLoaded" 
    xmlns="http://schemas.nativescript.org/tns.xsd" 
    xmlns:PullRefresh="nativescript-pulltorefresh">

    <ActionBar class="action-bar">
        
        <NavigationButton ios:visibility="collapsed" icon="res://menu" tap="onDrawerButtonTap"></NavigationButton>
        
        <ActionItem icon="res://navigation/menu" android:visibility="collapsed" tap="onDrawerButtonTap" ios.position="left">
        </ActionItem>
        <Label class="action-bar-title" text="Home"></Label>
    </ActionBar>

    <PullRefresh:PullToRefresh refresh="{{refreshList}}" id="pullToRefresh">
        <GridLayout class="page-content">
            <Label class="page-icon fa" text="&#xf015;"></Label>
            <Label class="page-placeholder" text="{{ data.today }}"></Label>
        </GridLayout>
    </PullRefresh>
</Page>
`

**Comment by programista25** [comment]
I suppose, that I'm using correct npm package. Below you can find my package.json file:
```
{
  "nativescript": {
    "id": "org.test.TestApp",
    "tns-android": {
      "version": "6.0.0"
    },
    "tns-ios": {
      "version": "6.0.1"
    }
  },
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "repository": "<fill-your-repository-here>",
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@nstudio/nativescript-pulltorefresh": "1.0.1",
    "nativescript-theme-core": "~1.0.6",
    "nativescript-ui-sidedrawer": "~7.0.0",
    "rxjs": "~6.5.0",
    "tns-core-modules": "~6.0.0"
  },
  "devDependencies": {
    "nativescript-dev-webpack": "~1.0.0",
    "node-sass": "^4.7.1",
    "tslint": "~5.11.0",
    "typescript": "~3.4.0"
  },
  "gitHead": "f28dbc60d74dd2cef4b645afd8fdd63bbb12c73e",
  "readme": "NativeScript Application"
}

```
I've also used this @nstudio package in xmlns:
```
<Page
    class="page"
    navigatingTo="onNavigatingTo"  
    loaded="onLoaded"
    xmlns="http://www.nativescript.org/tns.xsd"
    xmlns:lv="nativescript-ui-listview"
    xmlns:Card="nativescript-cardview"
    xmlns:PullRefresh="nativescript-pulltorefresh"
    xmlns:RL="nativescript-ripple">
```

**Comment by programista25** [comment]
My bad, I've forgot to change import statement to this: `import { PullToRefresh } from "@nstudio/nativescript-pulltorefresh";` in one of the service classes. No issue here.
